name: e_commerce_flutter
description: E-Commerce App built in flutter using GetX


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  get: ^4.6.6
  smooth_page_indicator: ^1.2.0+3
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.8.0
  animations: ^2.0.11
  stylish_bottom_bar: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  adaptive_icon_background : "#ffffff"
  adaptive_icon_foreground : "assets/images/logo.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
